[package]
name = "mem_scan"
version = "0.1.0"
edition = "2024"

[dependencies]
winapi = { version = "0.3.9", features = [
    "minwindef",
    "winnt",
    "processthreadsapi",
    "memoryapi",
    "handleapi",
    "sysinfoapi",
] }
